### ISSUE TITLE
Error when trying the example

### ISSUE THREAD

**Issue by lidaof** [igvteam/hic-straw#1]
Hi Jim,
Thanks for the nice library!
I am trying to including this library to our project, while trying the example, get following err:

![image](https://user-images.githubusercontent.com/102806/52231360-5f84b100-287f-11e9-8139-41fb3822bcac.png)

I created an empty html page [here](https://wangftp.wustl.edu/~dli/tmp/straw.html) and trying on the web console.

Thanks a lot.

**Comment by jrobinso** [comment]
OK, thanks for report.    I'll look into it.

**Comment by jrobinso** [comment]
Are you able to run the example html in the project  (by run I mean open
the html and see the output in the webpage)?

**Comment by lidaof** [comment]
Yeap, I just found the html in the example folder, I replaced the original hic url (gives 403 forbidden error) and the example works.

**Comment by jrobinso** [comment]
OK,  I'll look into the console error later today,  it should work from the
console.

**Comment by jrobinso** [comment]
I changed the hic file in the example to a public one,  I had forgotten the aidenlab files are restricted.

If the code doesn't run in the chrome console it doesn't run,  that is not a targetted mode although it is convenient.
