### ISSUE TITLE
Using es6 import uses old version of code?

### ISSUE THREAD

**Issue by cmdcolin** [igvteam/hic-straw#11]
Hi, I started some experiments with using hic-straw in jbrowse and it's working quite well. I made a small wrapper so generic-filehandle can be used with it (adapts our read(buffer, offset, length, pos) to read(pos, length) which is of course much simpler...just a legacy of trying to adapt the nodejs file reader api) so this is great.

I did have one concern, I saw that commonjs require('hic-straw') was working but the es6 import wasn't (produced negative file offsets in file reading, etc)

Might be related to package.json having this?

  "module": "dist/hic-straw_es6.js",  

This file appears to not be involved in the current build though, yet it is being deployed in the NPM bundles, so I wonder if this should actually say this

  "module": "dist/hic-straw.esm.js"

**Comment by jrobinso** [comment]
Yes I think you're correct.   Will fix.  Glad you're finding it useful.

**Comment by jrobinso** [comment]
This should be fixed now,  the correct file is "hic-straw.esm.js".   The package.json has been updated.   Fixed version is 1.2.2
