### ISSUE TITLE
getNormalizationOptions seems buggy?

### ISSUE THREAD

**Issue by lidaof** [igvteam/hic-straw#4]
Hi Jim,

I am testing one file and the norm options did contain KR, while when I use KR to pull the data, I got error: Normalization vectors not present in this file. I used the code just pulled from master.

![image](https://user-images.githubusercontent.com/102806/52663115-80768300-2ecb-11e9-800d-79281cbda34a.png)

**Comment by jrobinso** [comment]
OK, thanks, I'll look at it.

**Comment by lidaof** [comment]
Thanks Jim @jrobinso , the test file in the repo (test folder), I still see same error message, but contactRecords get filled:

![image](https://user-images.githubusercontent.com/102806/52664404-8883f200-2ece-11e9-8dc8-9485d4258a67.png)

**Comment by jrobinso** [comment]
Should be fixed.  Some faulty logic.

BTW,  the "nvi" parameter is a pointer to the position of the norm vector indeces in the file.   It is an optimization to speed initial load.   It doesn't help if loading a file only 1 time, but if you have files that will be loaded multiple times its a significant speedup.     You can get the parameter from straw.getNVI()

**Comment by lidaof** [comment]
Thanks Jim @jrobinso .
Would different norm option have different nvi parameters?

So how do I use the nvi parameter exactly? Should I just call the `getNVI()` function after initialize a new Straw instance?

Thanks again.

**Comment by jrobinso** [comment]
You call getNVI to get the value, which is a string  (byte position, byte size).   Then,  when you create a new Straw you can supply it,  as you do in your example above.   If you are only loading Encode and aidenlab hic files you don't need to worry about it,  I run a webservice lookup table for those.   Its an optional parameter in any event.

If you have public hic files that are not Encode or aidenlab send me a list of the URLs and I will populate the webservice for them.   The best format is a text file, 1 url per line.

**Comment by lidaof** [comment]
Thanks Jim @jrobinso. So I should make a new Straw based on a URL, call getNVI, and send you the url and the output of getNVI, next time when I make a new straw, I should provide a nvi value as well.
Do I understand this correctly?
Thanks.

**Comment by jrobinso** [comment]
If you have a large set of hic files that are public just send me the list and I'll add them to the webservice, you don't need to comput the NVI my script will do that.   Alternatively write a script yourself and include the nvi parameters in the Straw init as you were doing in the test.

**Comment by lidaof** [comment]
i see, thanks @jrobinso

**Comment by jrobinso** [comment]
This is optional of course, you haven't done it in the past,  but will speed up load time.
