### ISSUE TITLE
accept file Blob as input in config parameter

### ISSUE THREAD

**Issue by lidaof** [igvteam/hic-straw#5]
Hi Jim,

Previous version of straw seems works with file Blob as input when construct a new Straw instance, in this new version, how can I enable this?
I tried  `{file: fileBlob}` which is not working.
Thanks.

**Comment by jrobinso** [comment]
Hi @lidaof,  by previous versions I assume you mean the straw embedded in juicebox.    Apologies I forgot to port that to the stand-alone library.   I will do so soon, in the next day or so.

**Comment by lidaof** [comment]
Thank you @jrobinso for fast response.
I tried to say maybe version 0.2.0, the `path` attribute can also be a file Blog in the `config` object.

**Comment by jrobinso** [comment]
OK, I just pushed a fix.   I'll be doing a release by the end of the week.    To use a file blob specify the "blob" property  instead of "file" or "url" in the straw constructor.

**Comment by lidaof** [comment]
Yes, the new push works for me! Thank you Jim @jrobinso !
