### ISSUE TITLE
caught error while accessing GEO linked hic file

### ISSUE THREAD

**Issue by lidaof** [igvteam/hic-straw#6]
Hi Jim,

Nice to see juicebox.js can access GEO hic files through web.
I also tried [this link](https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2583nnn/GSM2583729/suppl/GSM2583729_H3K27ac_HiChIP_2.hic) with latest hic-straw (0.9.3), i got following error:

![image](https://user-images.githubusercontent.com/102806/57478153-dc993b00-725f-11e9-8b0d-a250de7dac6a.png)

same links works at juicebox.js site.
Did I miss any step? Thank you.

**Comment by jrobinso** [comment]
Sorry about that, I'll check it out.

**Comment by jrobinso** [comment]
I can't reproduce this error, could you give me more details on how to reproduce it?

**Comment by jrobinso** [comment]
How were you using hic-straw  (from node, script import, or es6 module)?   I found a problem with the es6 module,  its fixed in v0.9.4.

**Comment by lidaof** [comment]
Sorry Jim @jrobinso probably old code cached..i restarted node and see a new error:
![image](https://user-images.githubusercontent.com/102806/57597402-e13a4980-7514-11e9-9e4b-65d75c82e8a3.png)

code is example code:
![image](https://user-images.githubusercontent.com/102806/57597420-f57e4680-7514-11e9-968e-3b95a970bc7f.png)

Am I using the chr: All wrong way? Thank you :)

**Comment by jrobinso** [comment]
I'll look into it,   "All" is not a real chromosome, as you know, and there is no data for the parameters you have entered,  but it should give you a more reasonable error message than the one you see.   Thanks for the test case, in the future could you insert code int a ``` block rather than a screenshot?

**Comment by lidaof** [comment]
i see @jrobinso sure, will do. Thanks for looking into this.

**Comment by jrobinso** [comment]
I'm going to add a special method to access "all-all".   But could you tell me what you are going to do with the "all" data?

The real chromosomes should all work.

**Comment by lidaof** [comment]
Hi Jim @jrobinso , I don't really have such a use case yet. maybe when viewing genome wide interactions (like chr1->chr22)?

**Comment by jrobinso** [comment]
I'll add a method and special instructions for all-all,  but I can't think of a use case for your browser.  For interactions you probably will use bedPE files,  you won't be able to see anything in the rotated hic maps at whole genome view.

**Comment by lidaof** [comment]
Thank you Jim @jrobinso
