### ISSUE TITLE
more data fetch errors than previous version

### ISSUE THREAD

**Issue by lidaof** [igvteam/hic-straw#9]
Hi Jim,

Hope you are doing well and stay safe.

I recently upgrade hi-straw to 1.1.0, I found there are more errors on network tab trying to access same [HiC file url](https://data.4dnucleome.org/files-processed/4DNFI65MQOIJ/@@download/4DNFI65MQOIJ.hic)

version 1.1.0:
![image](https://user-images.githubusercontent.com/102806/79804837-756a7e80-832a-11ea-8b26-28a86c5291f5.png)

version:0.9.4
![image](https://user-images.githubusercontent.com/102806/79805060-f3c72080-832a-11ea-9fac-97c6a991a948.png)

fetched results are same though from my visual inspect..I don't see any usage update not sure if I did something wrong. Can you please check if I did something wrong? Thanks a lot.

**Comment by lidaof** [comment]
Hi Jim,

I replaced `import HicStraw from "hic-straw/dist/hic-straw_es6"` to `import HicStraw from "hic-straw/dist/hic-straw"`, this error is gone...not sure why...feel free to close it :)

**Comment by jrobinso** [comment]
@lidaof That's strange, I don't even know how that could work.  Anyway I would need a reproducible test case to look into it,  if it happens again reopen the issue.

**Comment by lidaof** [comment]
Sure, so far is good with me. I feel the new version is faster.

**Comment by jrobinso** [comment]
Yes it should be faster.   I figured out why your import works, the package.json defines "hic-straw_es6.js" as the "module" for the package.    What you are doing is fine,  I have a habit of being explicit and importing a specific file  (including the .js extension).

**Comment by lidaof** [comment]
make sense...my bad I missed reading the package.json :)

**Comment by jrobinso** [comment]
No problem, just noting what is going on here.  I dislike mysteries.   If bundling hic-straw with something else the rules for your package bundler (webpack or rollup) will apply.   If importing directly to a browser its rules will apply.   For maximum browser compatibility the full path to the js file, including the extension (.js) is the most robust, but if you are packaging hic-straw into a larger bundle it doesn't matter.
